from enum import Enum


class ErrorCode(str, Enum):
  MISSING_ADMIN_PASSWORD = "missing_admin_password"
  INVALID_ADMIN_PASSWORD = "invalid_admin_password"
  GAME_NOT_FOUND = "game_not_found"
  PERSON_NOT_FOUND = "person_not_found"
  PARTICIPANT_NOT_FOUND = "participant_not_found"
  GAME_MIN_PARTICIPANTS = "game_min_participants"
  INVALID_PARTICIPANT_NAME = "invalid_participant_name"
  DUPLICATE_PARTICIPANT_NAMES = "duplicate_participant_names"
  GAME_REVEAL_CONFLICT = "game_reveal_conflict"
  PERSON_ALREADY_IN_GAME = "person_already_in_game"
  NO_PARTICIPANTS_TO_ADD = "no_participants_to_add"
  GAME_INACTIVE = "game_inactive"
  TOKEN_NOT_FOUND = "token_not_found"
  LINK_NOT_FOUND = "link_not_found"
  ASSIGNMENT_NOT_READY = "assignment_not_ready"
  ASSIGNMENT_ALREADY_VIEWED = "assignment_already_viewed"
  INVALID_ASSIGNMENT_STATE = "invalid_assignment_state"
  NAME_REQUIRED = "name_required"
  NAME_DUPLICATE = "name_duplicate"
  FEATURE_DISABLED = "feature_disabled"
  MISSING_MASTER_PASSWORD = "missing_master_password"
  INVALID_MASTER_PASSWORD = "invalid_master_password"
  INVALID_PAYLOAD_BYTES = "invalid_payload_bytes"
  INVALID_REQUEST_BODY = "invalid_request_body"
  INVALID_PEOPLE_REQUEST = "invalid_people_request"
  WISHLIST_ITEM_NOT_FOUND = "wishlist_item_not_found"
